from __future__ import annotations

from pathlib import Path

from db.patterns import lookup_success_pattern


def _guess_name(repo: Path) -> str:
    return repo.name or "app"


def _entrypoint_for_language(repo: Path, lang: str) -> tuple[str, list[str]]:
    if lang == "rust":
        return "./target/release/" + _guess_name(repo), []
    if lang == "python":
        for candidate in ("main.py", "app.py"):
            if (repo / candidate).exists():
                return candidate, []
        return "main.py", []
    if lang == "node":
        if (repo / "dist/server.js").exists():
            return "node", ["dist/server.js"]
        if (repo / "src/index.ts").exists():
            return "node", ["src/index.ts"]
        return "node", ["index.js"]
    if lang == "go":
        return "./" + _guess_name(repo), []
    return "echo", ["Hello, capsule!"]


def _fallback_capsule_toml(repo: Path, lang: str) -> str:
    entrypoint, cmd = _entrypoint_for_language(repo, lang)
    cmd_line = ""
    if cmd:
        rendered = ", ".join(f'"{value}"' for value in cmd)
        cmd_line = f"cmd = [{rendered}]"
    return f"""# Capsule Manifest - Multi-Target Native v0.2
# Generated by: ato agent

schema_version = "0.2"
name = "{_guess_name(repo)}"
version = "0.1.0"
type = "app"
default_target = "cli"

[metadata]
description = "Capsule generated by the ato repository agent"

[requirements]

[targets.cli]
runtime = "source"
entrypoint = "{entrypoint}"
{cmd_line}

[storage]

[routing]
"""


def generate_node(state: dict) -> dict:
    repo = Path(state["repo_path"])
    manifest_path = repo / "capsule.toml"
    manifest_preexisting = manifest_path.exists()
    if manifest_path.exists():
        capsule_toml = manifest_path.read_text(encoding="utf-8")
    else:
        matched = lookup_success_pattern(
            state["config"].get("patterns_db", ""),
            repo,
            state.get("target_env") or {},
        )
        if matched:
            capsule_toml = matched
        else:
            capsule_toml = _fallback_capsule_toml(repo, state.get("detected_lang") or "unknown")
    return {
        **state,
        "capsule_toml": capsule_toml,
        "manifest_preexisting": manifest_preexisting,
    }
