from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from config import load_config
from db.patterns import init_db, store_success_pattern
from graph import run_agent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="ato repository agent loop")
    parser.add_argument("config_path", help="Path to the JSON config file generated by ato")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config = load_config(args.config_path)
    manifest_path = Path(config.repo_path) / "capsule.toml"

    Path(config.patterns_db).parent.mkdir(parents=True, exist_ok=True)
    Path(config.checkpoint_db).parent.mkdir(parents=True, exist_ok=True)
    init_db(config.patterns_db)

    result = run_agent(config)
    if result.get("all_tests_passed"):
        store_success_pattern(config.patterns_db, config, result)
    elif not result.get("manifest_preexisting") and manifest_path.exists():
        manifest_path.unlink()

    print(
        json.dumps(
            {
                "ok": bool(result.get("all_tests_passed")),
                "correction_count": result.get("correction_count", 0),
                "detected_lang": result.get("detected_lang"),
                "test_framework": result.get("test_framework"),
                "manifest_preexisting": bool(result.get("manifest_preexisting")),
            },
            ensure_ascii=False,
        )
    )
    return 0 if result.get("all_tests_passed") else 1


if __name__ == "__main__":
    sys.exit(main())
